/**
 * Autor: Maximiliano Pacheco Pérez
 * Fecha de Creación: 18/03/2023
 * Fecha de Actualización: 20/03/2023
 * Descripción: Programa que implementa el método de ordenación de Burbuja
 *              implementando una interfaz gráfica con el editor de NetBeans
 */
package metodos.de.ordenamiento;

public class MetodoBurbujaConInterfaz extends javax.swing.JFrame {

    public MetodoBurbujaConInterfaz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Título = new javax.swing.JLabel();
        EntradaDatos = new javax.swing.JTextField();
        Instrucciones = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();
        MensajeResultado = new javax.swing.JLabel();
        MostrarResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        Título.setBackground(new java.awt.Color(0, 0, 0));
        Título.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Título.setText("Método Burbuja");

        EntradaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaDatosActionPerformed(evt);
            }
        });

        Instrucciones.setText("Ingresa los Números a Ordenar separados por espacios \" \"");

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        MensajeResultado.setText("Resultado:");

        MostrarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(EntradaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MensajeResultado)
                                .addGap(18, 18, 18)
                                .addComponent(MostrarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Instrucciones))
                        .addGap(80, 80, 80))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(Título))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnOrdenar)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Título)
                .addGap(18, 18, 18)
                .addComponent(Instrucciones)
                .addGap(18, 18, 18)
                .addComponent(EntradaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrdenar)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MensajeResultado)
                    .addComponent(MostrarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntradaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaDatosActionPerformed

    private void MostrarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarResultadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MostrarResultadoActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // Obtener los números del JTextField
        String absorverDatos = EntradaDatos.getText();
        
        // Convertir la cadena de números a un arreglo de enteros
        String[] arregloNumeros = absorverDatos.split("\\s+");
        
        int[] numeros = new int[arregloNumeros.length];
        
        for (int i = 0; i < arregloNumeros.length; i++) {
            numeros[i] = Integer.parseInt(arregloNumeros[i]);
        }

        // Ordenar el arreglo de números utilizando el algoritmo de la burbuja
        for (int i = 0; i < numeros.length-1; i++) {
            for (int j = 0; j < numeros.length-i-1; j++) {
                if (numeros[j] > numeros[j+1]) { //Si NumeroActual > NumeroSiguiente
                    int aux = numeros[j];
                    numeros[j] = numeros[j+1];
                    numeros[j+1] = aux;
                }
   
            }
        }
        
         // Mostrar el resultado en el JTextArea
        String Resultado = "";
        for (int i = 0; i < numeros.length; i++) {
            Resultado += numeros[i] + " ";
        }
        MostrarResultado.setText(Resultado);
    }//GEN-LAST:event_btnOrdenarActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodoBurbujaConInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EntradaDatos;
    private javax.swing.JLabel Instrucciones;
    private javax.swing.JLabel MensajeResultado;
    private javax.swing.JTextField MostrarResultado;
    private javax.swing.JLabel Título;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
